/**
 * ============================================================================
 * INPUT VALIDATION SCHEMAS
 * ============================================================================
 *
 * TypeScript types are erased at compile time, so a handler annotated
 * `(cal: { cellId: number; x: number; y: number })` happily accepted
 * `{ cellId: "abc", x: NaN }` from the wire and wrote it straight into game
 * state. These schemas validate every untrusted boundary at runtime.
 *
 * Used by both the REST endpoints and the Socket.IO handlers.
 */
import { z } from "zod";

/** Telegram usernames: 3–32 chars, letters/digits/underscore, optional "@". */
export const telegramUsername = z
  .string()
  .trim()
  .regex(/^@?[A-Za-z0-9_]{3,32}$/, "Некорректное имя пользователя Telegram");

/** Hex colour such as #39FF14. */
export const hexColor = z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Некорректный цвет");

/** Board coordinate, expressed as a percentage of the board size. */
const percent = z.number().finite().min(0).max(100);

/** Identifier generated by the server (player_…, p_…, admin_user). */
export const playerId = z.string().trim().min(1).max(64);

// --- REST ------------------------------------------------------------------

export const loginSchema = z.object({
  name: z.string().trim().min(1, "Имя не может быть пустым").max(64),
  password: z.string().max(256).optional(),
  color: hexColor.optional(),
  role: z.enum(["admin", "player"]).optional(),
  telegramId: z.number().int().positive().optional(),
  telegramUsername: z.string().max(64).optional(),
});

export const registrationRequestSchema = z.object({
  username: telegramUsername,
});

/**
 * Registration request forwarded by the bot.
 *
 * Unlike the web form, the bot knows the numeric Telegram id and the private
 * chat id, which is what lets the approved player be recognised later without
 * a password.
 */
export const botRegistrationRequestSchema = z.object({
  username: telegramUsername,
  telegramId: z.number().int().positive(),
  chatId: z.number().int(),
  firstName: z.string().max(64).optional(),
});

export const botApproveRegistrationSchema = z.object({
  username: telegramUsername,
  admin: z.string().max(64).optional(),
  /** Numeric Telegram id, so the player can be recognised without a password. */
  telegramId: z.number().int().positive().optional(),
  /**
   * Who delivers the generated credentials to the player.
   * "bot" — the caller does it (it knows the private chat id);
   * "server" — this process sends the message itself (default, legacy callers).
   */
  deliverBy: z.enum(["bot", "server"]).optional(),
});

export const botRejectRegistrationSchema = z.object({
  username: telegramUsername,
  admin: z.string().max(64).optional(),
});

/**
 * Telegram Mini App handshake.
 *
 * `initData` is the raw signed string produced by the Telegram client and must
 * be forwarded verbatim — any re-encoding invalidates the HMAC.
 */
export const telegramAuthSchema = z.object({
  initData: z.string().min(1).max(4096),
  color: hexColor.optional(),
});

export const botApproveTurnSchema = z.object({
  playerId: z.string().trim().min(1).max(64),
  admin: z.string().max(64).optional(),
  confirmBonusUse: z.boolean().optional(),
  /**
   * How many rolls to open at once. Optional: older bot builds do not send it
   * and must keep working. The server clamps the value regardless.
   */
  turns: z.number().int().min(1).max(10).optional(),
  /**
   * Выдать ход только если заявка ещё открыта.
   *
   * Ставит ТОЛЬКО кнопка под заявкой в Telegram: она живёт в чате вечно, и
   * повторное нажатие выдавало ход второй раз. Выдача по инициативе
   * администратора (команда /turns, кнопки в админке) этот флаг не ставит —
   * там заявки может не быть вовсе, и это нормально.
   */
  requireRequest: z.boolean().optional(),
});

export const botRejectTurnSchema = z.object({
  playerId: z.string().trim().min(1).max(64),
  admin: z.string().max(64).optional(),
});

/** Личное сообщение игроку от администратора через бота. */
export const botMessagePlayerSchema = z.object({
  /** Хендл, псевдоним или id игрока — админ пишет то, что видит. */
  target: z.string().trim().min(1).max(64),
  text: z.string().trim().min(1).max(2000),
  admin: z.string().max(64).optional(),
});

/** Рассылка всем зарегистрированным игрокам. */
export const botBroadcastSchema = z.object({
  text: z.string().trim().min(1).max(2000),
  admin: z.string().max(64).optional(),
});

/** Выписка перемещений одного игрока. */
export const botPlayerHistorySchema = z.object({
  target: z.string().trim().min(1).max(64),
});

export const adminPasswordsSchema = z.object({
  password: z.string().min(1).max(256),
});

export const telegramUserSyncSchema = z.object({
  username: telegramUsername,
  chatId: z.number().int(),
});

// --- Socket.IO -------------------------------------------------------------

export const chatSendSchema = z.object({
  text: z.string().trim().min(1).max(500),
});

export const updatePlayerSchema = z.object({
  id: playerId,
  cell: z.number().int().min(0).max(64),
  color: hexColor.optional(),
  name: z.string().trim().min(1).max(64).optional(),
  chipImage: z.string().max(256).optional(),
});

export const registerPlayerSchema = z.object({
  name: z.string().trim().min(1).max(64),
  color: hexColor,
  password: z.string().max(256).optional(),
  chipImage: z.string().max(256).optional(),
});

export const setPlayerPasswordSchema = z.object({
  playerId,
  password: z.string().max(256).optional(),
});

export const calibrateCellSchema = z.object({
  cellId: z.number().int().min(0).max(64),
  x: percent,
  y: percent,
});

export const resetGameSchema = z.object({
  clearPlayers: z.boolean(),
  confirm: z.string().max(64).optional(),
});

export const updateAvatarSchema = z.object({
  id: playerId.optional(),
  // Data URLs are permitted but capped so the payload cannot be abused.
  avatar: z.string().max(512),
});

/** Background images may be a URL, a data URL, or null to reset. */
export const backgroundImageSchema = z.string().max(5_000_000).nullable();

/**
 * Parse untrusted input.
 * Returns a discriminated result instead of throwing, so callers can answer
 * with a helpful message rather than crashing the handler.
 */
export type ValidationResult<T> =
  { ok: true; data: T; error?: undefined } | { ok: false; data?: undefined; error: string };

export function validate<T>(schema: z.ZodType<T>, input: unknown): ValidationResult<T> {
  const result = schema.safeParse(input);
  if (result.success) return { ok: true, data: result.data };
  const first = result.error.issues[0];
  const path = first.path.length > 0 ? `${first.path.join(".")}: ` : "";
  return { ok: false, error: `${path}${first.message}` };
}
