/**
 * Registration flow, bot side.
 *
 * A player presses "Запросить регистрацию" (or sends /register). The bot
 * forwards the request to the game server together with the numeric Telegram
 * id and the private chat id, then notifies every administrator with two
 * buttons: ЗАРЕГИСТРИРОВАТЬ / ОТКАЗАТЬ.
 *
 * The password is generated by the game server — it is the component that
 * owns credentials — and returned to the bot exactly once so it can be
 * delivered to the player's private chat. It is never written to a log.
 */
import { Markup } from "telegraf";
import type { TelegramAsyncQueue } from "./asyncQueue.js";
import type { AdminManager } from "./adminManager.js";

/** Escape text before embedding it in a Telegram HTML message. */
export function escapeHtml(text: unknown): string {
  return String(text ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Normalise a handle to the "@name" form used as a key on both sides. */
export function normaliseHandle(username: string): string {
  const lower = username.trim().toLowerCase();
  return lower.startsWith("@") ? lower : `@${lower}`;
}

/**
 * Telegram's callback_data field is limited to 64 bytes, and a handle can be
 * 32 characters. "approve_reg:" plus "@" plus 32 leaves headroom, so the
 * handle is used directly rather than through a lookup table.
 */
export const MAX_CALLBACK_HANDLE = 40;

export interface RegistrationDeps {
  internalFetch: (pathname: string, init?: RequestInit) => Promise<Response>;
  queue: TelegramAsyncQueue;
  admins: AdminManager;
  webAppUrl?: string;
}

export interface RequestOutcome {
  /** Message to show the requesting player. */
  reply: string;
  /** True when administrators still need to be notified. */
  notifyAdmins: boolean;
  handle: string;
}

/**
 * Submit a registration request.
 *
 * The server is the single source of truth for whether the handle is already
 * a player or already queued, so no state is duplicated here.
 */
export async function submitRegistration(
  deps: RegistrationDeps,
  user: { username?: string; id: number; firstName?: string; chatId: number }
): Promise<RequestOutcome> {
  if (!user.username) {
    return {
      reply:
        "⚠️ У вашего аккаунта нет имени пользователя (@username).\n\n" +
        "Откройте настройки Telegram → «Имя пользователя», задайте его и повторите /register.\n" +
        "Без @username вас невозможно опознать в игре.",
      notifyAdmins: false,
      handle: "",
    };
  }

  const handle = normaliseHandle(user.username);
  if (handle.length > MAX_CALLBACK_HANDLE) {
    return {
      reply: "⚠️ Слишком длинное имя пользователя — обратитесь к администратору напрямую.",
      notifyAdmins: false,
      handle,
    };
  }

  let res: Response;
  try {
    res = await deps.internalFetch("/api/internal/registration-request", {
      method: "POST",
      body: JSON.stringify({
        username: handle,
        telegramId: user.id,
        chatId: user.chatId,
        firstName: user.firstName,
      }),
    });
  } catch {
    return {
      reply: "⚠️ Игровой сервер сейчас недоступен. Попробуйте через пару минут.",
      notifyAdmins: false,
      handle,
    };
  }

  const data = (await res.json().catch(() => ({}))) as {
    status?: string;
    error?: string;
  };

  if (!res.ok) {
    return {
      reply: `⚠️ Не удалось отправить заявку: ${data.error || "ошибка сервера"}`,
      notifyAdmins: false,
      handle,
    };
  }

  if (data.status === "already_registered") {
    return {
      reply:
        `✅ Вы уже зарегистрированы, ${escapeHtml(handle)}!\n\n` +
        `Нажмите «🎮 ИГРАТЬ» — пароль вводить не нужно.`,
      notifyAdmins: false,
      handle,
    };
  }

  if (data.status === "already_pending") {
    return {
      reply:
        "⏳ Ваша заявка уже отправлена и ждёт решения администратора.\n" +
        "Как только её одобрят, логин и пароль придут в этот чат.",
      notifyAdmins: false,
      handle,
    };
  }

  return {
    reply:
      "📨 <b>Заявка отправлена!</b>\n\n" +
      "Администратор получил уведомление. Как только он нажмёт «ЗАРЕГИСТРИРОВАТЬ», " +
      "в этот чат придут ваш логин и пароль, и кнопка «🎮 ИГРАТЬ» откроет игру.",
    notifyAdmins: true,
    handle,
  };
}

/** Send the approve/reject card to every administrator. */
export async function notifyAdminsAboutRequest(
  deps: RegistrationDeps,
  user: { handle: string; id: number; firstName?: string },
  resolveChatId: (adminHandle: string) => number | undefined
): Promise<void> {
  const text =
    `⚡ <b>НОВАЯ ЗАЯВКА НА РЕГИСТРАЦИЮ</b>\n\n` +
    `Игрок: <b>${escapeHtml(user.handle)}</b>\n` +
    (user.firstName ? `Имя: ${escapeHtml(user.firstName)}\n` : "") +
    `Telegram ID: <code>${user.id}</code>\n\n` +
    `<i>При регистрации бот сам создаст пароль и отправит его игроку.</i>`;

  const keyboard = Markup.inlineKeyboard([
    [Markup.button.callback("✅ ЗАРЕГИСТРИРОВАТЬ", `approve_reg:${user.handle}`)],
    [Markup.button.callback("❌ ОТКАЗАТЬ", `reject_reg:${user.handle}`)],
  ]);

  let delivered = 0;
  const unreachable: string[] = [];

  for (const adminHandle of deps.admins.getAdmins()) {
    const chatId = resolveChatId(adminHandle);

    // Telegram only accepts a numeric chat id for private chats: sending to
    // "@handle" works for channels, not for users. An administrator who has
    // never pressed /start is therefore unreachable, and the attempt is worth
    // a loud warning rather than a silent failure — otherwise registration
    // requests vanish with nobody noticing.
    if (chatId === undefined) {
      unreachable.push(adminHandle);
      continue;
    }

    try {
      await deps.queue.sendMessage(chatId, text, keyboard);
      delivered += 1;
    } catch (e) {
      unreachable.push(adminHandle);
      console.error(`[Bot] Could not notify admin ${adminHandle}:`, (e as Error)?.message || e);
    }
  }

  if (unreachable.length > 0) {
    console.warn(
      `[Bot] Registration request from ${user.handle}: ` +
        `${unreachable.length} administrator(s) unreachable (${unreachable.join(", ")}). ` +
        `They must send /start to this bot at least once.`
    );
  }

  if (delivered === 0) {
    console.error(
      `[Bot] NOBODY was notified about the registration request from ${user.handle}. ` +
        `Use /pending once an administrator has started the bot.`
    );
  }
}

/** Message delivered to a player once their registration is approved. */
export function credentialsMessage(handle: string, password: string): string {
  return (
    `✅ <b>РЕГИСТРАЦИЯ ОДОБРЕНА</b>\n\n` +
    `Логин: <code>${escapeHtml(handle)}</code>\n` +
    `Пароль: <code>${escapeHtml(password)}</code>\n\n` +
    `🔐 Сохраните пароль — он показывается один раз и нужен только для входа ` +
    `через браузер.\n` +
    `🎮 В Telegram пароль не нужен: нажмите кнопку «ИГРАТЬ» ниже, бот узнает вас сам.`
  );
}
