#!/usr/bin/env node
/**
 * Interactive-free .env bootstrapper.
 *
 * Usage:
 *   npm run setup-env -- --password 'your-admin-password' \
 *                        [--service-account ./service-account.json] \
 *                        [--project-id ...] [--database-id ...] \
 *                        [--admin @telegram_handle] [--bot-token ...] \
 *                        [--web-app-url https://...]
 *
 * Creates .env with freshly generated secrets. Never overwrites an existing
 * .env unless --force is passed.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
function arg(name) {
  const i = args.indexOf(`--${name}`);
  return i !== -1 && args[i + 1] && !args[i + 1].startsWith("--") ? args[i + 1] : undefined;
}
const has = (name) => args.includes(`--${name}`);

const ENV_PATH = path.resolve(process.cwd(), ".env");

if (fs.existsSync(ENV_PATH) && !has("force")) {
  console.error(
    `\n.env already exists at ${ENV_PATH}\n` +
      `Refusing to overwrite it. Pass --force to replace it (a .env.bak copy is kept).\n`
  );
  process.exit(1);
}

const password = arg("password");
if (!password) {
  console.error(
    "\nMissing --password.\n\n" + "  npm run setup-env -- --password 'your-strong-admin-password'\n"
  );
  process.exit(1);
}
if (password.length < 12) {
  console.warn(`[warn] Password is only ${password.length} characters. 12+ recommended.\n`);
}

// --- Admin password hash (must match src/utils/security.ts) ----------------
const salt = crypto.randomBytes(16).toString("hex");
const hash = crypto.pbkdf2Sync(password, salt, 100000, 32, "sha256").toString("hex");
const adminHash = `${salt}:${hash}`;

const sessionSecret = crypto.randomBytes(32).toString("hex");
const internalSecret = crypto.randomBytes(32).toString("hex");

// --- Optional service account ----------------------------------------------
let serviceAccountLine = 'FIREBASE_SERVICE_ACCOUNT=""';
let credentialsLine = 'GOOGLE_APPLICATION_CREDENTIALS=""';
let projectId = arg("project-id") || "";
let notes = [];

const saPath = arg("service-account");
if (saPath) {
  const resolved = path.resolve(saPath);
  if (!fs.existsSync(resolved)) {
    console.error(`\nService account file not found: ${resolved}\n`);
    process.exit(1);
  }
  let sa;
  try {
    sa = JSON.parse(fs.readFileSync(resolved, "utf8"));
  } catch {
    console.error(`\n${resolved} is not valid JSON.\n`);
    process.exit(1);
  }
  const missing = ["type", "project_id", "private_key", "client_email"].filter((k) => !sa[k]);
  if (missing.length) {
    console.error(
      `\n${resolved} does not look like a service-account key.\n` +
        `Missing field(s): ${missing.join(", ")}\n\n` +
        `Download the right file from:\n` +
        `  Firebase Console -> Project settings -> Service accounts\n` +
        `  -> "Generate new private key"\n`
    );
    process.exit(1);
  }
  if (sa.type !== "service_account") {
    console.error(`\nExpected "type":"service_account", found "${sa.type}".\n`);
    process.exit(1);
  }

  // Single-line JSON so it survives dotenv parsing.
  serviceAccountLine = `FIREBASE_SERVICE_ACCOUNT='${JSON.stringify(sa)}'`;
  projectId = projectId || sa.project_id;
  notes.push(`Service account embedded for project "${sa.project_id}" (${sa.client_email})`);
} else {
  notes.push("No service account supplied — Firestore stays disabled (local disk persistence).");
}

const databaseId = arg("database-id") || "";
const adminHandle = arg("admin") || "";
const botToken = arg("bot-token") || "";
const groupChatId = arg("group-chat-id") || "";
const webAppUrl = arg("web-app-url") || "";
const adminLogin = arg("admin-login") || "admin";

const env = `# Generated by: npm run setup-env
# ${new Date().toISOString()}
#
# ⚠️  SECRETS — never commit this file. It is covered by .gitignore.

NODE_ENV="production"
PORT="3000"
DATA_DIR="./data"
WEB_APP_URL="${webAppUrl}"

# Login name that authenticates against ADMIN_PASSWORD_HASH.
ADMIN_LOGIN="${adminLogin}"

# --- Security (required) ----------------------------------------------------
# PBKDF2 hash of the admin password. The password itself is not stored.
ADMIN_PASSWORD_HASH="${adminHash}"
SESSION_SECRET="${sessionSecret}"
INTERNAL_API_SECRET="${internalSecret}"

# --- Telegram ---------------------------------------------------------------
TELEGRAM_BOT_TOKEN="${botToken}"
TELEGRAM_GROUP_CHAT_ID="${groupChatId}"
TELEGRAM_ADMIN_USERNAME="${adminHandle}"

# --- Firestore (Admin SDK) --------------------------------------------------
# Option A: the key contents inline (this is what --service-account fills in).
${serviceAccountLine}

# Option B: path to the key file instead of the inline JSON above.
${credentialsLine}

FIREBASE_PROJECT_ID="${projectId}"
FIREBASE_FIRESTORE_DATABASE_ID="${databaseId}"

# --- Migration (optional) ---------------------------------------------------
# Only needed once, to migrate passwords written by a pre-hardening release.
LEGACY_AES_PASSWORD=""
`;

if (fs.existsSync(ENV_PATH)) {
  fs.copyFileSync(ENV_PATH, `${ENV_PATH}.bak`);
  notes.push(`Previous .env backed up to .env.bak`);
}

fs.writeFileSync(ENV_PATH, env, { mode: 0o600 });

console.log(`\n✅ Wrote ${ENV_PATH} (permissions 600)\n`);
for (const n of notes) console.log(`   • ${n}`);
console.log(`
Generated:
   • ADMIN_PASSWORD_HASH   (log in as ADMIN_LOGIN with the password you passed)
   • SESSION_SECRET        (signs session tokens)
   • INTERNAL_API_SECRET   (server <-> bot authentication)

Next:
   npm run build && npm start
   curl http://localhost:3000/healthz
`);
